// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_bezierldr[] =
"<?xml version=\"1.0\"?>"
"<!-- bezierldr.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.bezier</name>"
"        <implementation>csBezierLoader</implementation>"
"        <description>Crystal Space Bezier Mesh Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.loader.factory.bezier</name>"
"        <implementation>csBezierLoader</implementation>"
"        <description>Crystal Space Bezier Mesh Factory Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.bezier</name>"
"        <implementation>csBezierSaver</implementation>"
"        <description>Crystal Space Bezier Mesh Saver</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.factory.bezier</name>"
"        <implementation>csBezierSaver</implementation>"
"        <description>Crystal Space Bezier Mesh Factory Saver</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csBezierLoader_FACTORY_REGISTER_DEFINED 
  #define csBezierLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csBezierLoader) 
  #endif
  #ifndef csBezierLoader_FACTORY_REGISTER_DEFINED 
  #define csBezierLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csBezierLoader) 
  #endif
  #ifndef csBezierSaver_FACTORY_REGISTER_DEFINED 
  #define csBezierSaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csBezierSaver) 
  #endif
  #ifndef csBezierSaver_FACTORY_REGISTER_DEFINED 
  #define csBezierSaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csBezierSaver) 
  #endif

class bezierldr
{
SCF_REGISTER_STATIC_LIBRARY(bezierldr,metainfo_bezierldr)
  #ifndef csBezierLoader_FACTORY_REGISTERED 
  #define csBezierLoader_FACTORY_REGISTERED 
    csBezierLoader_StaticInit csBezierLoader_static_init__; 
  #endif
  #ifndef csBezierLoader_FACTORY_REGISTERED 
  #define csBezierLoader_FACTORY_REGISTERED 
    csBezierLoader_StaticInit csBezierLoader_static_init__; 
  #endif
  #ifndef csBezierSaver_FACTORY_REGISTERED 
  #define csBezierSaver_FACTORY_REGISTERED 
    csBezierSaver_StaticInit csBezierSaver_static_init__; 
  #endif
  #ifndef csBezierSaver_FACTORY_REGISTERED 
  #define csBezierSaver_FACTORY_REGISTERED 
    csBezierSaver_StaticInit csBezierSaver_static_init__; 
  #endif
public:
 bezierldr();
};
bezierldr::bezierldr() {}

}
