// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sndwaveout[] =
"<?xml version=\"1.0\"?>"
"<!-- sndwaveout.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.sound.driver.waveout</name>"
"        <implementation>csSoundDriverWaveOut</implementation>"
"        <description>Crystal Space waveOut Sound Driver</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSoundDriverWaveOut_FACTORY_REGISTER_DEFINED 
  #define csSoundDriverWaveOut_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSoundDriverWaveOut) 
  #endif

class sndwaveout
{
SCF_REGISTER_STATIC_LIBRARY(sndwaveout,metainfo_sndwaveout)
  #ifndef csSoundDriverWaveOut_FACTORY_REGISTERED 
  #define csSoundDriverWaveOut_FACTORY_REGISTERED 
    csSoundDriverWaveOut_StaticInit csSoundDriverWaveOut_static_init__; 
  #endif
public:
 sndwaveout();
};
sndwaveout::sndwaveout() {}

}
