// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_ball[] =
"<?xml version=\"1.0\"?>"
"<!-- ball.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.object.ball</name>"
"        <implementation>csBallMeshObjectType</implementation>"
"        <description>Crystal Space Ball Mesh Type</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csBallMeshObjectType_FACTORY_REGISTER_DEFINED 
  #define csBallMeshObjectType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csBallMeshObjectType) 
  #endif

class ball
{
SCF_REGISTER_STATIC_LIBRARY(ball,metainfo_ball)
  #ifndef csBallMeshObjectType_FACTORY_REGISTERED 
  #define csBallMeshObjectType_FACTORY_REGISTERED 
    csBallMeshObjectType_StaticInit csBallMeshObjectType_static_init__; 
  #endif
public:
 ball();
};
ball::ball() {}

}
