// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_ieplex[] =
"<?xml version=\"1.0\"?>"
"<!-- ieplex.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.modelconverter.multiplexer</name>"
"        <implementation>csModelConverterMultiplexer</implementation>"
"        <description>Multiplexer for Model Converters</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csModelConverterMultiplexer_FACTORY_REGISTER_DEFINED 
  #define csModelConverterMultiplexer_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csModelConverterMultiplexer) 
  #endif

class ieplex
{
SCF_REGISTER_STATIC_LIBRARY(ieplex,metainfo_ieplex)
  #ifndef csModelConverterMultiplexer_FACTORY_REGISTERED 
  #define csModelConverterMultiplexer_FACTORY_REGISTERED 
    csModelConverterMultiplexer_StaticInit csModelConverterMultiplexer_static_init__; 
  #endif
public:
 ieplex();
};
ieplex::ieplex() {}

}
