// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sndmod[] =
"<?xml version=\"1.0\"?>"
"<!-- sndmod.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.sound.loader.mod</name>"
"        <implementation>csModLoader</implementation>"
"        <description>MikMod Sound Loader</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csModLoader_FACTORY_REGISTER_DEFINED 
  #define csModLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csModLoader) 
  #endif

class sndmod
{
SCF_REGISTER_STATIC_LIBRARY(sndmod,metainfo_sndmod)
  #ifndef csModLoader_FACTORY_REGISTERED 
  #define csModLoader_FACTORY_REGISTERED 
    csModLoader_StaticInit csModLoader_static_init__; 
  #endif
public:
 sndmod();
};
sndmod::sndmod() {}

}
