// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sndplex[] =
"<?xml version=\"1.0\"?>"
"<!-- sndplex.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.sound.loader.multiplexer</name>"
"        <implementation>csSoundLoaderMultiplexer</implementation>"
"        <description>Sound Loader Multiplexer</description>"
"        <requires>"
"          <class>crystalspace.sound.loader.</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSoundLoaderMultiplexer_FACTORY_REGISTER_DEFINED 
  #define csSoundLoaderMultiplexer_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSoundLoaderMultiplexer) 
  #endif

class sndplex
{
SCF_REGISTER_STATIC_LIBRARY(sndplex,metainfo_sndplex)
  #ifndef csSoundLoaderMultiplexer_FACTORY_REGISTERED 
  #define csSoundLoaderMultiplexer_FACTORY_REGISTERED 
    csSoundLoaderMultiplexer_StaticInit csSoundLoaderMultiplexer_static_init__; 
  #endif
public:
 sndplex();
};
sndplex::sndplex() {}

}
