// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_csvosa3dl[] =
"<?xml version=\"1.0\"?>"
"<!-- csvosa3dl.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.network.vos.a3dl</name>"
"        <implementation>csVosA3DL</implementation>"
"        <description>Virtual Object System abstract 3D layer</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csVosA3DL_FACTORY_REGISTER_DEFINED 
  #define csVosA3DL_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csVosA3DL) 
  #endif

class csvosa3dl
{
SCF_REGISTER_STATIC_LIBRARY(csvosa3dl,metainfo_csvosa3dl)
  #ifndef csVosA3DL_FACTORY_REGISTERED 
  #define csVosA3DL_FACTORY_REGISTERED 
    csVosA3DL_StaticInit csVosA3DL_static_init__; 
  #endif
public:
 csvosa3dl();
};
csvosa3dl::csvosa3dl() {}

}
