// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_csavi[] =
"<?xml version=\"1.0\"?>"
"<!-- csavi.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.video.format.avi</name>"
"        <implementation>csAVIFormat</implementation>"
"        <description>CrystalSpace AVI format interface</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csAVIFormat_FACTORY_REGISTER_DEFINED 
  #define csAVIFormat_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csAVIFormat) 
  #endif

class csavi
{
SCF_REGISTER_STATIC_LIBRARY(csavi,metainfo_csavi)
  #ifndef csAVIFormat_FACTORY_REGISTERED 
  #define csAVIFormat_FACTORY_REGISTERED 
    csAVIFormat_StaticInit csAVIFormat_static_init__; 
  #endif
public:
 csavi();
};
csavi::csavi() {}

}
