// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_fountain[] =
"<?xml version=\"1.0\"?>"
"<!-- fountain.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.object.fountain</name>"
"        <implementation>csFountainMeshObjectType</implementation>"
"        <description>Crystal Space Fountain Mesh Type</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csFountainMeshObjectType_FACTORY_REGISTER_DEFINED 
  #define csFountainMeshObjectType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csFountainMeshObjectType) 
  #endif

class fountain
{
SCF_REGISTER_STATIC_LIBRARY(fountain,metainfo_fountain)
  #ifndef csFountainMeshObjectType_FACTORY_REGISTERED 
  #define csFountainMeshObjectType_FACTORY_REGISTERED 
    csFountainMeshObjectType_StaticInit csFountainMeshObjectType_static_init__; 
  #endif
public:
 fountain();
};
fountain::fountain() {}

}
