// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_rainldr[] =
"<?xml version=\"1.0\"?>"
"<!-- rainldr.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.factory.rain</name>"
"        <implementation>csRainFactoryLoader</implementation>"
"        <description>Crystal Space Rain Factory Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.loader.rain</name>"
"        <implementation>csRainLoader</implementation>"
"        <description>Crystal Space Rain Mesh Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.factory.rain</name>"
"        <implementation>csRainFactorySaver</implementation>"
"        <description>Crystal Space Rain Factory Saver</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.rain</name>"
"        <implementation>csRainSaver</implementation>"
"        <description>Crystal Space Rain Mesh Saver</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csRainFactoryLoader_FACTORY_REGISTER_DEFINED 
  #define csRainFactoryLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csRainFactoryLoader) 
  #endif
  #ifndef csRainLoader_FACTORY_REGISTER_DEFINED 
  #define csRainLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csRainLoader) 
  #endif
  #ifndef csRainFactorySaver_FACTORY_REGISTER_DEFINED 
  #define csRainFactorySaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csRainFactorySaver) 
  #endif
  #ifndef csRainSaver_FACTORY_REGISTER_DEFINED 
  #define csRainSaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csRainSaver) 
  #endif

class rainldr
{
SCF_REGISTER_STATIC_LIBRARY(rainldr,metainfo_rainldr)
  #ifndef csRainFactoryLoader_FACTORY_REGISTERED 
  #define csRainFactoryLoader_FACTORY_REGISTERED 
    csRainFactoryLoader_StaticInit csRainFactoryLoader_static_init__; 
  #endif
  #ifndef csRainLoader_FACTORY_REGISTERED 
  #define csRainLoader_FACTORY_REGISTERED 
    csRainLoader_StaticInit csRainLoader_static_init__; 
  #endif
  #ifndef csRainFactorySaver_FACTORY_REGISTERED 
  #define csRainFactorySaver_FACTORY_REGISTERED 
    csRainFactorySaver_StaticInit csRainFactorySaver_static_init__; 
  #endif
  #ifndef csRainSaver_FACTORY_REGISTERED 
  #define csRainSaver_FACTORY_REGISTERED 
    csRainSaver_StaticInit csRainSaver_static_init__; 
  #endif
public:
 rainldr();
};
rainldr::rainldr() {}

}
