// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_bezier[] =
"<?xml version=\"1.0\"?>"
"<!-- bezier.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.object.bezier</name>"
"        <implementation>csBezierMeshObjectType</implementation>"
"        <description>Crystal Space Bezier Mesh Type</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csBezierMeshObjectType_FACTORY_REGISTER_DEFINED 
  #define csBezierMeshObjectType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csBezierMeshObjectType) 
  #endif

class bezier
{
SCF_REGISTER_STATIC_LIBRARY(bezier,metainfo_bezier)
  #ifndef csBezierMeshObjectType_FACTORY_REGISTERED 
  #define csBezierMeshObjectType_FACTORY_REGISTERED 
    csBezierMeshObjectType_StaticInit csBezierMeshObjectType_static_init__; 
  #endif
public:
 bezier();
};
bezier::bezier() {}

}
