// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cssgiimg[] =
"<?xml version=\"1.0\"?>"
"<!-- cssgiimg.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphic.image.io.sgi</name>"
"        <implementation>csSGIImageIO</implementation>"
"        <description>CrystalSpace SGI image format I/O plugin</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSGIImageIO_FACTORY_REGISTER_DEFINED 
  #define csSGIImageIO_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSGIImageIO) 
  #endif

class cssgiimg
{
SCF_REGISTER_STATIC_LIBRARY(cssgiimg,metainfo_cssgiimg)
  #ifndef csSGIImageIO_FACTORY_REGISTERED 
  #define csSGIImageIO_FACTORY_REGISTERED 
    csSGIImageIO_StaticInit csSGIImageIO_static_init__; 
  #endif
public:
 cssgiimg();
};
cssgiimg::cssgiimg() {}

}
