// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_dsplex[] =
"<?xml version=\"1.0\"?>"
"<!-- dsplex.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.documentsystem.multiplex</name>"
"        <implementation>csMplexDocumentSystem</implementation>"
"        <description>Document system multiplexer</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csMplexDocumentSystem_FACTORY_REGISTER_DEFINED 
  #define csMplexDocumentSystem_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csMplexDocumentSystem) 
  #endif

class dsplex
{
SCF_REGISTER_STATIC_LIBRARY(dsplex,metainfo_dsplex)
  #ifndef csMplexDocumentSystem_FACTORY_REGISTERED 
  #define csMplexDocumentSystem_FACTORY_REGISTERED 
    csMplexDocumentSystem_StaticInit csMplexDocumentSystem_static_init__; 
  #endif
public:
 dsplex();
};
dsplex::dsplex() {}

}
