// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_furmaterial[] =
"<?xml version=\"1.0\"?>"
"<!-- hairmaterial.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.material.furmaterial</name>"
"        <implementation>FurMaterialType</implementation>"
"        <description>Fur Material Type Plugin</description>"
"        <requires>"
"          <class>crystalspace.graphics3d.</class>"
"        </requires>"
"      </class>"
"      <class>"
"        <name>crystalspace.physics.furphysics</name>"
"        <implementation>HairPhysicsControl</implementation>"
"        <description>Fur Material Type Plugin</description>"
"        <requires>"
"          <class>crystalspace.graphics3d.</class>"
"        </requires>"
"      </class>"
"      <class>"
"        <name>crystalspace.material.furstrandmaterial</name>"
"        <implementation>HairStrandGenerator</implementation>"
"        <description>Fur Strand MaterialPlugin</description>"
"        <requires>"
"          <class>crystalspace.graphics3d.</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef FurMaterialType_FACTORY_REGISTER_DEFINED 
  #define FurMaterialType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(FurMaterialType) 
  #endif
  #ifndef HairPhysicsControl_FACTORY_REGISTER_DEFINED 
  #define HairPhysicsControl_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(HairPhysicsControl) 
  #endif
  #ifndef HairStrandGenerator_FACTORY_REGISTER_DEFINED 
  #define HairStrandGenerator_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(HairStrandGenerator) 
  #endif

class furmaterial
{
SCF_REGISTER_STATIC_LIBRARY(furmaterial,metainfo_furmaterial)
  #ifndef FurMaterialType_FACTORY_REGISTERED 
  #define FurMaterialType_FACTORY_REGISTERED 
    FurMaterialType_StaticInit FurMaterialType_static_init__; 
  #endif
  #ifndef HairPhysicsControl_FACTORY_REGISTERED 
  #define HairPhysicsControl_FACTORY_REGISTERED 
    HairPhysicsControl_StaticInit HairPhysicsControl_static_init__; 
  #endif
  #ifndef HairStrandGenerator_FACTORY_REGISTERED 
  #define HairStrandGenerator_FACTORY_REGISTERED 
    HairStrandGenerator_StaticInit HairStrandGenerator_static_init__; 
  #endif
public:
 furmaterial();
};
furmaterial::furmaterial() {}

}
