// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_gmeshanimpdl[] =
"<?xml version=\"1.0\"?>"
"<!-- gmeshanimpdl.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.anim.pdlight</name>"
"        <implementation>csGenmeshAnimationPDLType</implementation>"
"        <description>Crystal Space Genmesh animation plugin for PD lights</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csGenmeshAnimationPDLType_FACTORY_REGISTER_DEFINED 
  #define csGenmeshAnimationPDLType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csGenmeshAnimationPDLType) 
  #endif

class gmeshanimpdl
{
SCF_REGISTER_STATIC_LIBRARY(gmeshanimpdl,metainfo_gmeshanimpdl)
  #ifndef csGenmeshAnimationPDLType_FACTORY_REGISTERED 
  #define csGenmeshAnimationPDLType_FACTORY_REGISTERED 
    csGenmeshAnimationPDLType_StaticInit csGenmeshAnimationPDLType_static_init__; 
  #endif
public:
 gmeshanimpdl();
};
gmeshanimpdl::gmeshanimpdl() {}

}
