// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_imgplex[] =
"<?xml version=\"1.0\"?>"
"<!-- imgplex.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphic.image.io.multiplex</name>"
"        <implementation>csMultiplexImageIO</implementation>"
"        <description>Image file format multiplex plug-in.</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csMultiplexImageIO_FACTORY_REGISTER_DEFINED 
  #define csMultiplexImageIO_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csMultiplexImageIO) 
  #endif

class imgplex
{
SCF_REGISTER_STATIC_LIBRARY(imgplex,metainfo_imgplex)
  #ifndef csMultiplexImageIO_FACTORY_REGISTERED 
  #define csMultiplexImageIO_FACTORY_REGISTERED 
    csMultiplexImageIO_StaticInit csMultiplexImageIO_static_init__; 
  #endif
public:
 imgplex();
};
imgplex::imgplex() {}

}
