// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_instmesh[] =
"<?xml version=\"1.0\"?>"
"<!-- instmesh.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.object.instmesh</name>"
"        <implementation>csInstmeshMeshObjectType</implementation>"
"        <description>Crystal Space Instancing Mesh Type</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csInstmeshMeshObjectType_FACTORY_REGISTER_DEFINED 
  #define csInstmeshMeshObjectType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csInstmeshMeshObjectType) 
  #endif

class instmesh
{
SCF_REGISTER_STATIC_LIBRARY(instmesh,metainfo_instmesh)
  #ifndef csInstmeshMeshObjectType_FACTORY_REGISTERED 
  #define csInstmeshMeshObjectType_FACTORY_REGISTERED 
    csInstmeshMeshObjectType_StaticInit csInstmeshMeshObjectType_static_init__; 
  #endif
public:
 instmesh();
};
instmesh::instmesh() {}

}
