// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_partphys_ode[] =
"<?xml version=\"1.0\"?>"
"<!-- particles.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.particles.physics.ode</name>"
"	<implementation>csODEParticlePhysics</implementation>"
"        <description>Crystal Space ODE Particle Physics</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csODEParticlePhysics_FACTORY_REGISTER_DEFINED 
  #define csODEParticlePhysics_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csODEParticlePhysics) 
  #endif

class partphys_ode
{
SCF_REGISTER_STATIC_LIBRARY(partphys_ode,metainfo_partphys_ode)
  #ifndef csODEParticlePhysics_FACTORY_REGISTERED 
  #define csODEParticlePhysics_FACTORY_REGISTERED 
    csODEParticlePhysics_StaticInit csODEParticlePhysics_static_init__; 
  #endif
public:
 partphys_ode();
};
partphys_ode::partphys_ode() {}

}
