// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_povie[] =
"<?xml version=\"1.0\"?>"
"<!-- povie.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.modelconverter.pov</name>"
"        <implementation>csModelConverterPOV</implementation>"
"        <description>POV Model Converter</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csModelConverterPOV_FACTORY_REGISTER_DEFINED 
  #define csModelConverterPOV_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csModelConverterPOV) 
  #endif

class povie
{
SCF_REGISTER_STATIC_LIBRARY(povie,metainfo_povie)
  #ifndef csModelConverterPOV_FACTORY_REGISTERED 
  #define csModelConverterPOV_FACTORY_REGISTERED 
    csModelConverterPOV_StaticInit csModelConverterPOV_static_init__; 
  #endif
public:
 povie();
};
povie::povie() {}

}
