// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_rapid[] =
"<?xml version=\"1.0\"?>"
"<!-- rapid.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.collisiondetection.rapid</name>"
"        <implementation>csRapidCollideSystem</implementation>"
"        <description>CrystalSpace RAPID CD System</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csRapidCollideSystem_FACTORY_REGISTER_DEFINED 
  #define csRapidCollideSystem_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csRapidCollideSystem) 
  #endif

class rapid
{
SCF_REGISTER_STATIC_LIBRARY(rapid,metainfo_rapid)
  #ifndef csRapidCollideSystem_FACTORY_REGISTERED 
  #define csRapidCollideSystem_FACTORY_REGISTERED 
    csRapidCollideSystem_StaticInit csRapidCollideSystem_static_init__; 
  #endif
public:
 rapid();
};
rapid::rapid() {}

}
