// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sndwav[] =
"<?xml version=\"1.0\"?>"
"<!-- sndwav.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.sound.loader.wav</name>"
"        <implementation>csSoundLoader_WAV</implementation>"
"        <description>WAV Sound Loader</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSoundLoader_WAV_FACTORY_REGISTER_DEFINED 
  #define csSoundLoader_WAV_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSoundLoader_WAV) 
  #endif

class sndwav
{
SCF_REGISTER_STATIC_LIBRARY(sndwav,metainfo_sndwav)
  #ifndef csSoundLoader_WAV_FACTORY_REGISTERED 
  #define csSoundLoader_WAV_FACTORY_REGISTERED 
    csSoundLoader_WAV_StaticInit csSoundLoader_WAV_static_init__; 
  #endif
public:
 sndwav();
};
sndwav::sndwav() {}

}
