// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_simpcon[] =
"<?xml version=\"1.0\"?>"
"<!-- simpcon.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.console.output.simple</name>"
"        <implementation>csSimpleConsole</implementation>"
"        <description>Crystal Space simple output console</description>"
"        <requires>"
"          <class>crystalspace.kernel.</class>"
"          <class>crystalspace.graphics3d.</class>"
"          <class>crystalspace.graphics2d.</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSimpleConsole_FACTORY_REGISTER_DEFINED 
  #define csSimpleConsole_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSimpleConsole) 
  #endif

class simpcon
{
SCF_REGISTER_STATIC_LIBRARY(simpcon,metainfo_simpcon)
  #ifndef csSimpleConsole_FACTORY_REGISTERED 
  #define csSimpleConsole_FACTORY_REGISTERED 
    csSimpleConsole_StaticInit csSimpleConsole_static_init__; 
  #endif
public:
 simpcon();
};
simpcon::simpcon() {}

}
