// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_stars[] =
"<?xml version=\"1.0\"?>"
"<!-- stars.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.object.stars</name>"
"        <implementation>csStarsMeshObjectType</implementation>"
"        <description>Crystal Space Stars Mesh Type</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csStarsMeshObjectType_FACTORY_REGISTER_DEFINED 
  #define csStarsMeshObjectType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csStarsMeshObjectType) 
  #endif

class stars
{
SCF_REGISTER_STATIC_LIBRARY(stars,metainfo_stars)
  #ifndef csStarsMeshObjectType_FACTORY_REGISTERED 
  #define csStarsMeshObjectType_FACTORY_REGISTERED 
    csStarsMeshObjectType_StaticInit csStarsMeshObjectType_static_init__; 
  #endif
public:
 stars();
};
stars::stars() {}

}
