// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_starldr[] =
"<?xml version=\"1.0\"?>"
"<!-- starldr.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.factory.stars</name>"
"        <implementation>csStarFactoryLoader</implementation>"
"        <description>Crystal Space Star Factory Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.loader.stars</name>"
"        <implementation>csStarLoader</implementation>"
"        <description>Crystal Space Star Mesh Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.factory.stars</name>"
"        <implementation>csStarFactorySaver</implementation>"
"        <description>Crystal Space Star Factory Saver</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.stars</name>"
"        <implementation>csStarSaver</implementation>"
"        <description>Crystal Space Star Mesh Saver</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csStarFactoryLoader_FACTORY_REGISTER_DEFINED 
  #define csStarFactoryLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csStarFactoryLoader) 
  #endif
  #ifndef csStarLoader_FACTORY_REGISTER_DEFINED 
  #define csStarLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csStarLoader) 
  #endif
  #ifndef csStarFactorySaver_FACTORY_REGISTER_DEFINED 
  #define csStarFactorySaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csStarFactorySaver) 
  #endif
  #ifndef csStarSaver_FACTORY_REGISTER_DEFINED 
  #define csStarSaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csStarSaver) 
  #endif

class starldr
{
SCF_REGISTER_STATIC_LIBRARY(starldr,metainfo_starldr)
  #ifndef csStarFactoryLoader_FACTORY_REGISTERED 
  #define csStarFactoryLoader_FACTORY_REGISTERED 
    csStarFactoryLoader_StaticInit csStarFactoryLoader_static_init__; 
  #endif
  #ifndef csStarLoader_FACTORY_REGISTERED 
  #define csStarLoader_FACTORY_REGISTERED 
    csStarLoader_StaticInit csStarLoader_static_init__; 
  #endif
  #ifndef csStarFactorySaver_FACTORY_REGISTERED 
  #define csStarFactorySaver_FACTORY_REGISTERED 
    csStarFactorySaver_StaticInit csStarFactorySaver_static_init__; 
  #endif
  #ifndef csStarSaver_FACTORY_REGISTERED 
  #define csStarSaver_FACTORY_REGISTERED 
    csStarSaver_StaticInit csStarSaver_static_init__; 
  #endif
public:
 starldr();
};
starldr::starldr() {}

}
