// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_spiral[] =
"<?xml version=\"1.0\"?>"
"<!-- spiral.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.object.spiral</name>"
"        <implementation>csSpiralMeshObjectType</implementation>"
"        <description>Crystal Space Spiral Mesh Type</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSpiralMeshObjectType_FACTORY_REGISTER_DEFINED 
  #define csSpiralMeshObjectType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSpiralMeshObjectType) 
  #endif

class spiral
{
SCF_REGISTER_STATIC_LIBRARY(spiral,metainfo_spiral)
  #ifndef csSpiralMeshObjectType_FACTORY_REGISTERED 
  #define csSpiralMeshObjectType_FACTORY_REGISTERED 
    csSpiralMeshObjectType_StaticInit csSpiralMeshObjectType_static_init__; 
  #endif
public:
 spiral();
};
spiral::spiral() {}

}
