// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_soft3d[] =
"<?xml version=\"1.0\"?>"
"<!-- soft3d.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphics3d.software</name>"
"        <implementation>csSoftwareGraphics3D</implementation>"
"        <description>Software graphics driver for Crystal Space</description>"
"        <requires>"
"          <class>crystalspace.font.server.</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSoftwareGraphics3D_FACTORY_REGISTER_DEFINED 
  #define csSoftwareGraphics3D_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSoftwareGraphics3D) 
  #endif

class soft3d
{
SCF_REGISTER_STATIC_LIBRARY(soft3d,metainfo_soft3d)
  #ifndef csSoftwareGraphics3D_FACTORY_REGISTERED 
  #define csSoftwareGraphics3D_FACTORY_REGISTERED 
    csSoftwareGraphics3D_StaticInit csSoftwareGraphics3D_static_init__; 
  #endif
public:
 soft3d();
};
soft3d::soft3d() {}

}
