// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sndogg[] =
"<?xml version=\"1.0\"?>"
"<!-- sndogg.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.sound.loader.ogg</name>"
"        <implementation>csOggLoader</implementation>"
"        <description>Ogg Vorbis Sound Loader</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csOggLoader_FACTORY_REGISTER_DEFINED 
  #define csOggLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csOggLoader) 
  #endif

class sndogg
{
SCF_REGISTER_STATIC_LIBRARY(sndogg,metainfo_sndogg)
  #ifndef csOggLoader_FACTORY_REGISTERED 
  #define csOggLoader_FACTORY_REGISTERED 
    csOggLoader_StaticInit csOggLoader_static_init__; 
  #endif
public:
 sndogg();
};
sndogg::sndogg() {}

}
