// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_thingldr[] =
"<?xml version=\"1.0\"?>"
"<!-- thingldr.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.factory.thing</name>"
"        <implementation>csThingFactoryLoader</implementation>"
"        <description>Crystal Space Thing Mesh Factory Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.loader.thing</name>"
"        <implementation>csThingLoader</implementation>"
"        <description>Crystal Space Thing Mesh Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.factory.thing</name>"
"        <implementation>csThingFactorySaver</implementation>"
"        <description>Crystal Space Thing Mesh Factory Saver</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.thing</name>"
"        <implementation>csThingSaver</implementation>"
"        <description>Crystal Space Thing Mesh Saver</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csThingFactoryLoader_FACTORY_REGISTER_DEFINED 
  #define csThingFactoryLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csThingFactoryLoader) 
  #endif
  #ifndef csThingLoader_FACTORY_REGISTER_DEFINED 
  #define csThingLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csThingLoader) 
  #endif
  #ifndef csThingFactorySaver_FACTORY_REGISTER_DEFINED 
  #define csThingFactorySaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csThingFactorySaver) 
  #endif
  #ifndef csThingSaver_FACTORY_REGISTER_DEFINED 
  #define csThingSaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csThingSaver) 
  #endif

class thingldr
{
SCF_REGISTER_STATIC_LIBRARY(thingldr,metainfo_thingldr)
  #ifndef csThingFactoryLoader_FACTORY_REGISTERED 
  #define csThingFactoryLoader_FACTORY_REGISTERED 
    csThingFactoryLoader_StaticInit csThingFactoryLoader_static_init__; 
  #endif
  #ifndef csThingLoader_FACTORY_REGISTERED 
  #define csThingLoader_FACTORY_REGISTERED 
    csThingLoader_StaticInit csThingLoader_static_init__; 
  #endif
  #ifndef csThingFactorySaver_FACTORY_REGISTERED 
  #define csThingFactorySaver_FACTORY_REGISTERED 
    csThingFactorySaver_StaticInit csThingFactorySaver_static_init__; 
  #endif
  #ifndef csThingSaver_FACTORY_REGISTERED 
  #define csThingSaver_FACTORY_REGISTERED 
    csThingSaver_StaticInit csThingSaver_static_init__; 
  #endif
public:
 thingldr();
};
thingldr::thingldr() {}

}
