// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_thing[] =
"<?xml version=\"1.0\"?>"
"<!-- thing.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.object.thing</name>"
"        <implementation>csThingObjectType</implementation>"
"        <description>Crystal Space Thing Mesh Type</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csThingObjectType_FACTORY_REGISTER_DEFINED 
  #define csThingObjectType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csThingObjectType) 
  #endif

class thing
{
SCF_REGISTER_STATIC_LIBRARY(thing,metainfo_thing)
  #ifndef csThingObjectType_FACTORY_REGISTERED 
  #define csThingObjectType_FACTORY_REGISTERED 
    csThingObjectType_StaticInit csThingObjectType_static_init__; 
  #endif
public:
 thing();
};
thing::thing() {}

}
