// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_aws2[] =
"<?xml version=\"1.0\"?>"
"<!-- aws2.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.window.alternatemanager2</name>"
"        <implementation>awsManager2</implementation>"
"        <description>Crystal Space alternate window manager version 2.0.alpha</description>"
"      </class>      "
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef awsManager2_FACTORY_REGISTER_DEFINED 
  #define awsManager2_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(awsManager2) 
  #endif

class aws2
{
SCF_REGISTER_STATIC_LIBRARY(aws2,metainfo_aws2)
  #ifndef awsManager2_FACTORY_REGISTERED 
  #define awsManager2_FACTORY_REGISTERED 
    awsManager2_StaticInit awsManager2_static_init__; 
  #endif
public:
 aws2();
};
aws2::aws2() {}

}
