// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_aseie[] =
"<?xml version=\"1.0\"?>"
"<!-- aseie.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.modelconverter.ase</name>"
"        <implementation>csModelConverterASE</implementation>"
"        <description>ASE Model Converter</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csModelConverterASE_FACTORY_REGISTER_DEFINED 
  #define csModelConverterASE_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csModelConverterASE) 
  #endif

class aseie
{
SCF_REGISTER_STATIC_LIBRARY(aseie,metainfo_aseie)
  #ifndef csModelConverterASE_FACTORY_REGISTERED 
  #define csModelConverterASE_FACTORY_REGISTERED 
    csModelConverterASE_StaticInit csModelConverterASE_static_init__; 
  #endif
public:
 aseie();
};
aseie::aseie() {}

}
