// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cswalimg[] =
"<?xml version=\"1.0\"?>"
"<!-- cswalimg.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphic.image.io.wal</name>"
"        <implementation>csWALImageIO</implementation>"
"        <description>CrystalSpace WAL image format I/O plugin</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csWALImageIO_FACTORY_REGISTER_DEFINED 
  #define csWALImageIO_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csWALImageIO) 
  #endif

class cswalimg
{
SCF_REGISTER_STATIC_LIBRARY(cswalimg,metainfo_cswalimg)
  #ifndef csWALImageIO_FACTORY_REGISTERED 
  #define csWALImageIO_FACTORY_REGISTERED 
    csWALImageIO_StaticInit csWALImageIO_static_init__; 
  #endif
public:
 cswalimg();
};
cswalimg::cswalimg() {}

}
