// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_chunklod[] =
"<?xml version=\"1.0\"?>"
"<!-- chunklod.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.object.terrain.chunklod</name>"
"        <implementation>csChunkLodTerrainType</implementation>"
"        <description>Crystal Space Chunked LOD Terrain</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csChunkLodTerrainType_FACTORY_REGISTER_DEFINED 
  #define csChunkLodTerrainType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csChunkLodTerrainType) 
  #endif

class chunklod
{
SCF_REGISTER_STATIC_LIBRARY(chunklod,metainfo_chunklod)
  #ifndef csChunkLodTerrainType_FACTORY_REGISTERED 
  #define csChunkLodTerrainType_FACTORY_REGISTERED 
    csChunkLodTerrainType_StaticInit csChunkLodTerrainType_static_init__; 
  #endif
public:
 chunklod();
};
chunklod::chunklod() {}

}
