// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_foliageldr[] =
"<?xml version=\"1.0\"?>"
"<!-- foliageldr.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.factory.foliage</name>"
"        <implementation>csFoliageFactoryLoader</implementation>"
"        <description>Crystal Space Foliage Mesh Factory Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.loader.foliage</name>"
"        <implementation>csFoliageMeshLoader</implementation>"
"        <description>Crystal Space Foliage Mesh Mesh Loader</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.factory.foliage</name>"
"        <implementation>csFoliageFactorySaver</implementation>"
"        <description>Crystal Space Foliage Mesh Factory Saver</description>"
"      </class>"
"      <class>"
"        <name>crystalspace.mesh.saver.foliage</name>"
"        <implementation>csFoliageMeshSaver</implementation>"
"        <description>Crystal Space Foliage Mesh Mesh Saver</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csFoliageFactoryLoader_FACTORY_REGISTER_DEFINED 
  #define csFoliageFactoryLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csFoliageFactoryLoader) 
  #endif
  #ifndef csFoliageMeshLoader_FACTORY_REGISTER_DEFINED 
  #define csFoliageMeshLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csFoliageMeshLoader) 
  #endif
  #ifndef csFoliageFactorySaver_FACTORY_REGISTER_DEFINED 
  #define csFoliageFactorySaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csFoliageFactorySaver) 
  #endif
  #ifndef csFoliageMeshSaver_FACTORY_REGISTER_DEFINED 
  #define csFoliageMeshSaver_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csFoliageMeshSaver) 
  #endif

class foliageldr
{
SCF_REGISTER_STATIC_LIBRARY(foliageldr,metainfo_foliageldr)
  #ifndef csFoliageFactoryLoader_FACTORY_REGISTERED 
  #define csFoliageFactoryLoader_FACTORY_REGISTERED 
    csFoliageFactoryLoader_StaticInit csFoliageFactoryLoader_static_init__; 
  #endif
  #ifndef csFoliageMeshLoader_FACTORY_REGISTERED 
  #define csFoliageMeshLoader_FACTORY_REGISTERED 
    csFoliageMeshLoader_StaticInit csFoliageMeshLoader_static_init__; 
  #endif
  #ifndef csFoliageFactorySaver_FACTORY_REGISTERED 
  #define csFoliageFactorySaver_FACTORY_REGISTERED 
    csFoliageFactorySaver_StaticInit csFoliageFactorySaver_static_init__; 
  #endif
  #ifndef csFoliageMeshSaver_FACTORY_REGISTERED 
  #define csFoliageMeshSaver_FACTORY_REGISTERED 
    csFoliageMeshSaver_StaticInit csFoliageMeshSaver_static_init__; 
  #endif
public:
 foliageldr();
};
foliageldr::foliageldr() {}

}
