// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_fontplex[] =
"<?xml version=\"1.0\"?>"
"<!-- fontplex.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.font.server.multiplexer</name>"
"        <implementation>csFontServerMultiplexor</implementation>"
"        <description>Crystal Space font server multiplexor</description>"
"        <requires>"
"          <class>crystalspace.font.server.</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csFontServerMultiplexor_FACTORY_REGISTER_DEFINED 
  #define csFontServerMultiplexor_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csFontServerMultiplexor) 
  #endif

class fontplex
{
SCF_REGISTER_STATIC_LIBRARY(fontplex,metainfo_fontplex)
  #ifndef csFontServerMultiplexor_FACTORY_REGISTERED 
  #define csFontServerMultiplexor_FACTORY_REGISTERED 
    csFontServerMultiplexor_StaticInit csFontServerMultiplexor_static_init__; 
  #endif
public:
 fontplex();
};
fontplex::fontplex() {}

}
