// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_foliage[] =
"<?xml version=\"1.0\"?>"
"<!-- foliage.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.object.foliage</name>"
"        <implementation>csFoliageMeshObjectType</implementation>"
"        <description>Crystal Space Foliage Mesh Type</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csFoliageMeshObjectType_FACTORY_REGISTER_DEFINED 
  #define csFoliageMeshObjectType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csFoliageMeshObjectType) 
  #endif

class foliage
{
SCF_REGISTER_STATIC_LIBRARY(foliage,metainfo_foliage)
  #ifndef csFoliageMeshObjectType_FACTORY_REGISTERED 
  #define csFoliageMeshObjectType_FACTORY_REGISTERED 
    csFoliageMeshObjectType_StaticInit csFoliageMeshObjectType_static_init__; 
  #endif
public:
 foliage();
};
foliage::foliage() {}

}
