// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_ie3ds[] =
"<?xml version=\"1.0\"?>"
"<!-- ie3ds.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.modelconverter.3ds</name>"
"        <implementation>csModelConverter3ds</implementation>"
"        <description>3ds Model Converter</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csModelConverter3ds_FACTORY_REGISTER_DEFINED 
  #define csModelConverter3ds_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csModelConverter3ds) 
  #endif

class ie3ds
{
SCF_REGISTER_STATIC_LIBRARY(ie3ds,metainfo_ie3ds)
  #ifndef csModelConverter3ds_FACTORY_REGISTERED 
  #define csModelConverter3ds_FACTORY_REGISTERED 
    csModelConverter3ds_StaticInit csModelConverter3ds_static_init__; 
  #endif
public:
 ie3ds();
};
ie3ds::ie3ds() {}

}
