// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_mdlie[] =
"<?xml version=\"1.0\"?>"
"<!-- mdlie.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.modelconverter.mdl</name>"
"        <implementation>csModelConverterMDL</implementation>"
"        <description>MDL Model Converter</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csModelConverterMDL_FACTORY_REGISTER_DEFINED 
  #define csModelConverterMDL_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csModelConverterMDL) 
  #endif

class mdlie
{
SCF_REGISTER_STATIC_LIBRARY(mdlie,metainfo_mdlie)
  #ifndef csModelConverterMDL_FACTORY_REGISTERED 
  #define csModelConverterMDL_FACTORY_REGISTERED 
    csModelConverterMDL_StaticInit csModelConverterMDL_static_init__; 
  #endif
public:
 mdlie();
};
mdlie::mdlie() {}

}
