// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_md2ie[] =
"<?xml version=\"1.0\"?>"
"<!-- md2ie.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.modelconverter.md2</name>"
"        <implementation>csModelConverterMD2</implementation>"
"        <description>MD2 Model Converter</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csModelConverterMD2_FACTORY_REGISTER_DEFINED 
  #define csModelConverterMD2_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csModelConverterMD2) 
  #endif

class md2ie
{
SCF_REGISTER_STATIC_LIBRARY(md2ie,metainfo_md2ie)
  #ifndef csModelConverterMD2_FACTORY_REGISTERED 
  #define csModelConverterMD2_FACTORY_REGISTERED 
    csModelConverterMD2_StaticInit csModelConverterMD2_static_init__; 
  #endif
public:
 md2ie();
};
md2ie::md2ie() {}

}
