// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_particles[] =
"<?xml version=\"1.0\"?>"
"<!-- particles.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.object.particles</name>"
"        <implementation>csParticlesType</implementation>"
"        <description>Crystal Space Particle System</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csParticlesType_FACTORY_REGISTER_DEFINED 
  #define csParticlesType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csParticlesType) 
  #endif

class particles
{
SCF_REGISTER_STATIC_LIBRARY(particles,metainfo_particles)
  #ifndef csParticlesType_FACTORY_REGISTERED 
  #define csParticlesType_FACTORY_REGISTERED 
    csParticlesType_StaticInit csParticlesType_static_init__; 
  #endif
public:
 particles();
};
particles::particles() {}

}
