// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_partphys_simple[] =
"<?xml version=\"1.0\"?>"
"<!-- particles.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.particles.physics.simple</name>"
"		<implementation>csParticlesPhysicsSimple</implementation>"
"        <description>Crystal Space Simple Particle Physics</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csParticlesPhysicsSimple_FACTORY_REGISTER_DEFINED 
  #define csParticlesPhysicsSimple_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csParticlesPhysicsSimple) 
  #endif

class partphys_simple
{
SCF_REGISTER_STATIC_LIBRARY(partphys_simple,metainfo_partphys_simple)
  #ifndef csParticlesPhysicsSimple_FACTORY_REGISTERED 
  #define csParticlesPhysicsSimple_FACTORY_REGISTERED 
    csParticlesPhysicsSimple_StaticInit csParticlesPhysicsSimple_static_init__; 
  #endif
public:
 partphys_simple();
};
partphys_simple::partphys_simple() {}

}
