// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pvs[] =
"<?xml version=\"1.0\"?>"
"<!-- frustvis.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.culling.pvs</name>"
"        <implementation>csPVSVis</implementation>"
"        <description>Fast culling that calculates PVS before run-time.</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csPVSVis_FACTORY_REGISTER_DEFINED 
  #define csPVSVis_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csPVSVis) 
  #endif

class pvs
{
SCF_REGISTER_STATIC_LIBRARY(pvs,metainfo_pvs)
  #ifndef csPVSVis_FACTORY_REGISTERED 
  #define csPVSVis_FACTORY_REGISTERED 
    csPVSVis_StaticInit csPVSVis_static_init__; 
  #endif
public:
 pvs();
};
pvs::pvs() {}

}
