// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sprie[] =
"<?xml version=\"1.0\"?>"
"<!-- sprie.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.modelconverter.spr</name>"
"        <implementation>csModelConverterSPR</implementation>"
"        <description>SPR Model Converter</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csModelConverterSPR_FACTORY_REGISTER_DEFINED 
  #define csModelConverterSPR_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csModelConverterSPR) 
  #endif

class sprie
{
SCF_REGISTER_STATIC_LIBRARY(sprie,metainfo_sprie)
  #ifndef csModelConverterSPR_FACTORY_REGISTERED 
  #define csModelConverterSPR_FACTORY_REGISTERED 
    csModelConverterSPR_StaticInit csModelConverterSPR_static_init__; 
  #endif
public:
 sprie();
};
sprie::sprie() {}

}
