// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sndiff[] =
"<?xml version=\"1.0\"?>"
"<!-- sndiff.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.sound.loader.iff</name>"
"        <implementation>csSoundLoader_IFF</implementation>"
"        <description>IFF Sound Loader</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSoundLoader_IFF_FACTORY_REGISTER_DEFINED 
  #define csSoundLoader_IFF_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSoundLoader_IFF) 
  #endif

class sndiff
{
SCF_REGISTER_STATIC_LIBRARY(sndiff,metainfo_sndiff)
  #ifndef csSoundLoader_IFF_FACTORY_REGISTERED 
  #define csSoundLoader_IFF_FACTORY_REGISTERED 
    csSoundLoader_IFF_StaticInit csSoundLoader_IFF_static_init__; 
  #endif
public:
 sndiff();
};
sndiff::sndiff() {}

}
