// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_softshader[] =
"<?xml version=\"1.0\"?>"
"<!-- softshader.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.graphics3d.shader.software</name>"
"        <implementation>csSoftShader</implementation>"
"        <description>Software specific shaderprogram provider for Graphics3D</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSoftShader_FACTORY_REGISTER_DEFINED 
  #define csSoftShader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSoftShader) 
  #endif

class softshader
{
SCF_REGISTER_STATIC_LIBRARY(softshader,metainfo_softshader)
  #ifndef csSoftShader_FACTORY_REGISTERED 
  #define csSoftShader_FACTORY_REGISTERED 
    csSoftShader_StaticInit csSoftShader_static_init__; 
  #endif
public:
 softshader();
};
softshader::softshader() {}

}
