// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sndaiff[] =
"<?xml version=\"1.0\"?>"
"<!-- sndaiff.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.sound.loader.aiff</name>"
"        <implementation>csSoundLoader_AIFF</implementation>"
"        <description>AIFF Sound Loader</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSoundLoader_AIFF_FACTORY_REGISTER_DEFINED 
  #define csSoundLoader_AIFF_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSoundLoader_AIFF) 
  #endif

class sndaiff
{
SCF_REGISTER_STATIC_LIBRARY(sndaiff,metainfo_sndaiff)
  #ifndef csSoundLoader_AIFF_FACTORY_REGISTERED 
  #define csSoundLoader_AIFF_FACTORY_REGISTERED 
    csSoundLoader_AIFF_StaticInit csSoundLoader_AIFF_static_init__; 
  #endif
public:
 sndaiff();
};
sndaiff::sndaiff() {}

}
