// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_sndoal[] =
"<?xml version=\"1.0\"?>"
"<!-- sndoal.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.sound.render.openal</name>"
"        <implementation>csSoundRenderOpenAL</implementation>"
"        <description>OpenAL 3D Sound Driver for Crystal Space</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csSoundRenderOpenAL_FACTORY_REGISTER_DEFINED 
  #define csSoundRenderOpenAL_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csSoundRenderOpenAL) 
  #endif

class sndoal
{
SCF_REGISTER_STATIC_LIBRARY(sndoal,metainfo_sndoal)
  #ifndef csSoundRenderOpenAL_FACTORY_REGISTERED 
  #define csSoundRenderOpenAL_FACTORY_REGISTERED 
    csSoundRenderOpenAL_StaticInit csSoundRenderOpenAL_static_init__; 
  #endif
public:
 sndoal();
};
sndoal::sndoal() {}

}
