// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_videorecorder[] =
"<?xml version=\"1.0\"?>"
"<!-- videorecorder.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.utilities.videorecorder</name>"
"        <implementation>csVideoRecorder</implementation>"
"        <description>Realtime movie recorder</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csVideoRecorder_FACTORY_REGISTER_DEFINED 
  #define csVideoRecorder_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csVideoRecorder) 
  #endif

class videorecorder
{
SCF_REGISTER_STATIC_LIBRARY(videorecorder,metainfo_videorecorder)
  #ifndef csVideoRecorder_FACTORY_REGISTERED 
  #define csVideoRecorder_FACTORY_REGISTERED 
    csVideoRecorder_StaticInit csVideoRecorder_static_init__; 
  #endif
public:
 videorecorder();
};
videorecorder::videorecorder() {}

}
