#ifndef IDS_H_INCLUDED
#define IDS_H_INCLUDED

enum APPIDS
{
    // menu IDs
    //---------------------------------------------------------------//
    IDM_SAVEASBITMAP = wxID_HIGHEST + 1,

    // tool IDs
    //---------------------------------------------------------------//
    IDT_FIRST_TOOLMARKER,

    IDT_GRID,
    IDT_SHADOW,
    IDT_TOOL,
    IDT_ELLIPSESHP,
    IDT_ROOTNODESHP,
    IDT_SELECTORSHP,
    IDT_DEFAULTSELSHP,
    IDT_SEQUENCESELSHP,
    IDT_RANDOMSELSHP,
    IDT_DECORATORSHP,
    IDT_LOOPDECSHP,
    IDT_NEGRETURNDECSHP,
    IDT_EXECLIMITDECSHP,
    IDT_CHKCONDITIONSHP,
    IDT_TRIGGERSHP,
    IDT_MESSAGETRGSHP,
    IDT_TRIGGERTRGSHP,
    IDT_SEQUENCETRGSHP,
    IDT_PROPCHANGETRGSHP,
    IDT_INVENTORYTRGSHP,
    IDT_MESHSELECTTRGSHP,
    IDT_ENTERSECTORTRGSHP,
    IDT_TIMEOUTTRGSHP,
    IDT_OPERATIONTRGSHP,
    IDT_WATCHTRGSHP,
    IDT_ACTIONSHP,

    IDT_TEXTSHP,
    IDT_EDITTEXTSHP,
    //IDT_BITMAPSHP,

    IDT_CURVESHP,
    IDT_LINKSHP,
    //IDT_ORTHOSHP,
    //IDT_ALIGN_LEFT,
    //IDT_ALIGN_RIGHT,
    //IDT_ALIGN_TOP,
    //IDT_ALIGN_BOTTOM,
    //IDT_ALIGN_MIDDLE,
    //IDT_ALIGN_CENTER,

    IDT_LAST_TOOLMARKER,
	
    //IDM_AUTOLAYOUT_FIRST,
    //IDM_AUTOLAYOUT_LAST = IDM_AUTOLAYOUT_FIRST + 100,

    // other constrols
    //---------------------------------------------------------------//
    //IDT_COLORPICKER
};

enum BTNodeType
{

   IDT_ROOT,
   IDT_DEFAULT,
   IDT_RANDOM,
   IDT_SEQUENTIAL,
   IDT_INVENTORY,
   IDT_MESSAGE,
   IDT_MESH_SELECT,
   IDT_OPERATION,
   IDT_PROP_CHANGE,
   IDT_SEQ_FINISH,
   IDT_TIMEOUT,
   IDT_TRIGGER,
   IDT_WATCH,
   IDT_ENTER_SECTOR,
   IDT_LOOP,
   IDT_NEGATERETURN,
   IDT_EXE_LIMIT,
   IDT_PARAM_CHCK,
   IDT_ACTION
};

enum TreeEventIds
{
 ID_ACTIVATED,
 ID_SEL_CHANGED,
 ID_SEL_CHANGING,
 ID_KEY_DOWN,
 ID_COLLAPSED,
 ID_EXPANDED
};

#endif // IDS_H_INCLUDED
